### ISSUE TITLE
It's removing "disabled" attribute on start

### ISSUE THREAD

**Issue by rosostolato** [johannesjo/angular2-promise-buttons#34]
I have a `mat-button` that is being disabled by form control validation property... but `promiseBtn` is removing `disabled` attribute at start:

```
<button
        mat-icon-button
        color="success"
        *ngIf="row.editing"
        (click)="confirmEditCreate(row)"
        [disabled]="row.form.invalid"
        [promiseBtn]="saveButtonSubscription"
></button>
```

So it should be like the following screenshot, but `disabled` is being removed:
![image](https://user-images.githubusercontent.com/27731641/74187870-2dddbd00-4c2c-11ea-95b9-7d2464eed510.png)

while I was debugging the code, I could see that it calls this method on start, which is causing the issue ([line 123](https://github.com/johannesjo/angular2-promise-buttons/blob/1044c1880981a263adb93d10c681deb4b65989fb/src/promise-btn.directive.ts#L123))
```
  removeLoadingClass(el: any) {
    if (typeof this.cfg.btnLoadingClass === 'string') {
      el.classList.remove(this.cfg.btnLoadingClass);
    }
  }
```

**Comment by johannesjo** [comment]
Thank you very much for reporting. I'll try to check this tomorrow.

**Comment by johannesjo** [comment]
May I ask which version of angular you are using?

**Comment by rosostolato** [comment]
Well, in this project I'm using angular 7.2.16 and I didn't test it in other projects with latest angular. Do you think it can be the problem?

**Comment by johannesjo** [comment]
Might be. There actually is some code to enable/disable the button, but normally this shouldn't be called until it is clicked. You can disable this in the configuration of the library (by setting `disableBtn to false`). Does that make any difference?

**Comment by rosostolato** [comment]
Yep, that is what I did, but the disable feature is great while the button is loading. I will create a standalone project and try to reproduce it to share with you

**Comment by PieterVanPoyer** [comment]
Hi

This is a standalone reproduction of a related problem in my opinion:
https://stackblitz.com/edit/angular-ivy-d3tray
The disabled setting of the button is removed by the angular2-promise-buttons.
After the setting of the disabled flag, an own disables setting (fe a form.invalid) is not working anymore.

Kind regards
Pieter

**Comment by johannesjo** [comment]
@PieterVanPoyer thank you! I'll try to have a look as soon as I can. Meanwhile PRs are welcome! :)

**Comment by johannesjo** [comment]
Thanks to @PieterVanPoyer this can be closed. I also published a new patch release.

**Comment by Gillardo** [comment]
What version is this fix in, as i am experiencing the problem and i am running version 4.0.7, which i believe is the latest version available.  I have tried to update the example above to load 4.0.7 but it errors

**Comment by Gillardo** [comment]
As you see same problem

![image](https://user-images.githubusercontent.com/7406381/85145699-e3f18d00-b244-11ea-838f-2889ad0fa42a.png)

My code is very simple

```
        <button type="button"
                class="btn btn-outline-primary"
                (click)="onSave()"
                [disabled]="user.username === ''"
                [promiseBtn]="saveSubscription">Save
        </button>
```

**Comment by johannesjo** [comment]
@Gillardo seems like I forgot to pull the changes in locally before making a new release.... Very sorry. The update should be out now!

**Comment by Gillardo** [comment]
I am sorry, but i have upgraded to 4.0.8 and the problem is still there.

Not sure if this helps in any way, but here is the problem

![image](https://user-images.githubusercontent.com/7406381/85176954-ec60bc80-b272-11ea-843c-f96df871a593.png)

But if i click my button, which should be disabled (which calls a web api, not sure if that matters), then it works after that and the code is correct.

![image](https://user-images.githubusercontent.com/7406381/85176994-04d0d700-b273-11ea-9721-a027e0067407.png)

**Comment by Gillardo** [comment]
Also, if i revert to version 4.0.5, this is working

**Comment by johannesjo** [comment]
You're right. I published another release with a fix for the issue.

**Comment by Gillardo** [comment]
4.0.9 works great! thank you
